### ISSUE TITLE
how to change the logo of the rapidoc

### ISSUE THREAD

**Issue by agronomofiorentini** [meztez/rapidoc#3]
Dear Contributors,
I would like to ask you if you could tell me how to change the logo & name of the RapiDoc documentation that is generated by the `rapidoc ` R package.

I have tried using the following way, but it does not work, could you please suggest how I might be able to accomplish this?

```
plumber::pr_set_docs("rapidoc", logo="https://i.ibb.co/T8Q3jXq/logo.jpg", header="blabla")
```

Thanks

**Comment by meztez** [comment]
```r
plumber::pr_set_docs("rapidoc", slots='<img slot="logo" src="https://i.ibb.co/T8Q3jXq/logo.jpg" width=36px style=\"margin-left:7px\"/>')
```
According to rapidoc documentation : https://rapidocweb.com/api.html#slots

Also this package help manual on `rapidoc_spec`, look at the example.
